### ISSUE TITLE
Use git submodules to include frontend and backend repos

### ISSUE THREAD

**Issue by ctgraham** [Caligula1022/ccvg_integral#1]
The existing repo loses the change and attribution history on the frontend and backend repos by copying the files in a single commit instead of incorporating the git history of the existing repos:
https://github.com/ulsdevteam/ccvgd-backend/
and
https://github.com/ulsdevteam/ccvgd-frontend/

To resolve this, incorporate the original code as git submodules.

**Comment by Caligula1022** [comment]
Hi Clinton,

Sorry for the late response. Recently, I've been very busy because of the job search. So thank you for your patient guidance.

On this issue, I ran those instructions you sent me earlier. But nothing happened. Do I need to push my code again after executing those commands? Because any time it comes to updating git, I'm very careful, I'm worried about breaking existing code.

As for traefik, I just uploaded the latest code. I'm not sure if what I've done is up to what you want, you can try it and let me know if you have any problems and I'll improve. Here is the page when I access port 8080.

***@***.***

For hardcoded credentials, I may need a little bit more time. I promise to do it as soon as possible.

I appreciate the time you put into this.

Kind regards,

Yifei Tai
Master’s of Information Science
School of Computing and Information
University of Pittsburgh






From: Clinton Graham ***@***.***>
Date: Friday, August 12, 2022 at 9:36 AM
To: Caligula1022/ccvg_integral ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Caligula1022/ccvg_integral] Use git submodules to include frontend and backend repos (Issue #1)

The existing repo loses the change and attribution history on the frontend and backend repos by copying the files in a single commit instead of incorporating the git history of the existing repos:
https://github.com/ulsdevteam/ccvgd-backend/
and
https://github.com/ulsdevteam/ccvgd-frontend/

To resolve this, incorporate the original code as git submodules.

**Comment by ctgraham** [comment]
Yes, changes made to your local git repo will need to be pushed to the remote to be visible on GitHub and reusable by others.

Changes made through git will be extremely robust because you can always check out an older commit if you find that you've introduced a regression.  This is further strengthened with the use of branches and tags.  For example, you can tag the application at the commits which you received, and then push your changes and then add another tag to what you have tested as a stable release.  You can checkout a tag just as a branch, and thus can switch the code to an arbitrary known good point.

**Comment by Caligula1022** [comment]
I understand, thanks!


From: Clinton Graham ***@***.***>
Date: Friday, August 12, 2022 at 2:56 PM
To: Caligula1022/ccvg_integral ***@***.***>
Cc: Caligula1022 ***@***.***>, Comment ***@***.***>
Subject: Re: [Caligula1022/ccvg_integral] Use git submodules to include frontend and backend repos (Issue #1)

Yes, changes made to your local git repo will need to be pushed to the remote to be visible on GitHub and reusable by others.

Changes made through git will be extremely robust because you can always check out an older commit if you find that you've introduced a regression. This is further strengthened with the use of branches and tags. For example, you can tag the application at the commits which you received, and then push your changes and then add another tag to what you have tested as a stable release. You can checkout a tag just as a branch, and thus can switch the code to an arbitrary known good point.

**Comment by Caligula1022** [comment]
This issue has been solved. Please check.

**Comment by ctgraham** [comment]
Looks good; thanks!

As you make additional changes to the submodules, you'll commit and push them to the individual repositories, then also commit the new submodule hashes in this repository.

**Comment by Caligula1022** [comment]
Yessir!
